const METHOD_ADD_QUEST = 'addQuest'
const METHOD_PAY_FOR_QUEST = 'payForQuest'
const METHOD_SET_QUEST_OUTCOME = 'setQuestOutcome'
const METHOD_CANCEL_QUEST_ENTRY= 'cancelQuestEntry'
const METHOD_CANCEL_QUEST = 'cancelQuest'
const METHOD_CLAIM_REFUND = 'claimRefund'

module.exports = {
    METHOD_ADD_QUEST,
    METHOD_PAY_FOR_QUEST,
    METHOD_SET_QUEST_OUTCOME,
    METHOD_CANCEL_QUEST_ENTRY,
    METHOD_CANCEL_QUEST,
    METHOD_CLAIM_REFUND
}