const METHOD_CREATE_PRIZE_TABLE = 'createPrizeTable'
const METHOD_CREATE_TOURNAMENT = 'createTournament'
const METHOD_ENTER_TOURNAMENT = 'enterTournament'
const METHOD_COMPLETE_TOURNAMENT = 'completeTournament'
const METHOD_CLAIM_TOURNAMENT_PRIZE = 'claimTournamentPrize'
const METHOD_CLAIM_TOURNAMENT_REFUND = 'claimTournamentRefund'

module.exports = {
    METHOD_CREATE_PRIZE_TABLE,
    METHOD_CREATE_TOURNAMENT,
    METHOD_ENTER_TOURNAMENT,
    METHOD_COMPLETE_TOURNAMENT,
    METHOD_CLAIM_TOURNAMENT_PRIZE,
    METHOD_CLAIM_TOURNAMENT_REFUND
}